apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: elj1lru2c-nodejs
  janus-idp.io/tekton: elj1lru2c-nodejs
  backstage.io/kubernetes-id: elj1lru2c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: elj1lru2c-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
